# type_of_missing_and_how.missing_how_type { #missingness_analyzer.type_of_missing_and_how.missing_how_type }

```python
type_of_missing_and_how.missing_how_type(df, alpha=0.05)
```

This function will analyze and print out a report of missing values and the type of missingness in the dataset.

There are three types of missing data:
- MCAR: Missing completely at random, which can be tested using the chi-squared function from the SciPy package. 
The chi-squared function helps test the independence of the columns in the dataset to determine whether 
the missingness is completely independent of each other
- MAR: Missing at random. If the missingness is not MCAR, it may be MAR; 
however, further domain knowledge is required to make this determination.
- MNAR: Missing not at random. Domain expertise is required to determine whether this type of missingness is present.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                                     | Default    |
|--------|--------|---------------------------------------------------------------------------------|------------|
| df     |        | A pandas dataframe to analyze missingness.                                      | _required_ |
| alpha  |        | The significant level to test the p.value that result from the chi-squared test | `0.05`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type             | Description                                                                                                                                                                                                                                              |
|--------|------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | pandas.DataFrame | The table contains two columns: one shows the names of the columns in the dataset, and the other indicates whether each column is MCAR, MAR, or MNAR. If the value is True, the column is MCAR. If the value is False, the column is either MAR or MNAR. |